name: lhkem
services:
  mongo:
    image: mongo:7
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER:-root}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD:-password}
      MONGO_INITDB_DATABASE: lhkem
    ports:
      - "${MONGO_PORT:-27017}:27017"
    volumes:
      - mongo-data:/data/db
      - ./mongo-init:/docker-entrypoint-initdb.d
    networks:
      - lhkem-net
 
  backend:
    container_name: backend
    build: ../backend
    environment:
      JWT_SECRET: super-secret-key
      MONGO_URL: mongodb://root:password@mongo:27017/lhkem?authSource=admin
      NODE_ENV: production
      PORT: ${PORT:-3000}
    ports:
      - "${PORT:-3000}:3000"
    volumes:
      - ../backend/uploads:/app/uploads
    depends_on:
      - mongo
    networks:
      - lhkem-net
  
  frontend:
    container_name: frontend
    build:
      context: ../frontend
      args:
        VITE_API_URL: ${VITE_API_URL:-http://localhost:3000}
    ports:
      - ${FRONTEND_PORT:-5173}:80
    environment:
      - NGINX_PROXY=${NGINX_PROXY:-http://backend:3000}
      - NGINX_PORT=${NGINX_PORT:-80}
    depends_on:
      - backend
    networks:
      - lhkem-net

volumes:
  mongo-data:
    driver: local
  backend-uploads:
    driver: local

networks:
  lhkem-net:
    driver: bridge